[pytest]
addopts = -s -v
testpaths = tests
python_files = *_test.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    user: Маркировка для тестов, связанных с пользователями.
    pet: Маркировка для тестов, связанных с животными.
    store: Маркировка для тестов, связанных с магазином.
    regression: Маркировка для регрессионных тестов.
